/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 08 20:38:51 GMT 2016
 */

package com.chiralbehaviors.CoRE.json;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jooq.DSLContext;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.fasterxml.jackson.databind.Module;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CoREModule_ESTest extends CoREModule_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        CoREModule coREModule0 = new CoREModule();
        assertEquals("CoREModule", coREModule0.getModuleName());
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        CoREModule coREModule0 = new CoREModule((DSLContext) null);
        // Undeclared exception!
        try {
            coREModule0.setupModule((Module.SetupContext) null);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            assertThrownBy("com.chiralbehaviors.CoRE.json.CoREModule", e);
        }
    }
}
