/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 08 20:23:00 GMT 2016
 */

package com.chiralbehaviors.CoRE.json;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class RecordResolver_ESTest extends RecordResolver_ESTest_scaffolding {
    @Test
    public void notGeneratedAnyTest() {
        // EvoSuite did not generate any tests
    }
}
