query q {
  allFilms {
    films {
      title
      episodeID
      director
      producers
      vehicleConnection {
        vehicles {
          name
          model
          manufacturers
          pilotConnection {
            pilots {
              name
              birthYear
              eyeColor
              gender
            }
          }
        }
      }
    }
  }
}