query q {
  films {
    title
    episodeID
    director
    producers 
    vehicles {
      name
      model
      manufacturers 
      pilots {
        name
        birthYear
        eyeColor
        gender
      } 
    }
  }
}