/**
 * Scaffolding file used to store all the setups needed to run
 * tests automatically generated by EvoSuite
 * Fri Apr 08 20:12:18 GMT 2016
 */

package com.chiralbehaviors.CoRE.domain;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;

@EvoSuiteClassExclude
public class ExistentialRuleform_ESTest_scaffolding {

    @BeforeClass
    public static void initEvoSuiteFramework() {
        org.evosuite.runtime.RuntimeSettings.className = "com.chiralbehaviors.CoRE.domain.ExistentialRuleform";
        org.evosuite.runtime.GuiSupport.initialize();
        org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
        org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
        org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
        org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
        org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
        org.evosuite.runtime.classhandling.JDKClassResetter.init();
        initializeClasses();
        org.evosuite.runtime.Runtime.getInstance()
                                    .resetRuntime();
    }

    private static void initializeClasses() {
        org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ExistentialRuleform_ESTest_scaffolding.class.getClassLoader(),
                                                                               "com.chiralbehaviors.CoRE.domain.ExistentialRuleform",
                                                                               "com.chiralbehaviors.CoRE.phantasm.Phantasm");
    }

    private static void resetClasses() {
        org.evosuite.runtime.classhandling.ClassResetter.getInstance()
                                                        .setClassLoader(ExistentialRuleform_ESTest_scaffolding.class.getClassLoader());

        org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses("org.jooq.SQLDialect",
                                                                          "com.chiralbehaviors.CoRE.jooq.enums.ExistentialDomain",
                                                                          "com.chiralbehaviors.CoRE.jooq.enums.ValueType",
                                                                          "org.postgresql.PGProperty",
                                                                          "org.jooq.impl.AbstractStore",
                                                                          "org.jooq.impl.AbstractRecord",
                                                                          "org.jooq.impl.TableRecordImpl",
                                                                          "org.jooq.impl.UpdatableRecordImpl",
                                                                          "com.chiralbehaviors.CoRE.jooq.tables.records.ExistentialRecord",
                                                                          "com.chiralbehaviors.CoRE.domain.StatusCode",
                                                                          "org.jooq.impl.AbstractQueryPart",
                                                                          "org.jooq.Clause",
                                                                          "org.jooq.impl.AbstractTable",
                                                                          "org.jooq.impl.TableImpl",
                                                                          "org.jooq.impl.SchemaImpl",
                                                                          "com.chiralbehaviors.CoRE.jooq.Ruleform",
                                                                          "org.jooq.impl.Fields",
                                                                          "org.jooq.impl.DefaultDataType",
                                                                          "org.jooq.impl.DefaultBinding",
                                                                          "org.jooq.Converters",
                                                                          "org.jooq.Converters$1",
                                                                          "org.jooq.util.cubrid.CUBRIDDataType",
                                                                          "org.jooq.util.derby.DerbyDataType",
                                                                          "org.jooq.util.firebird.FirebirdDataType",
                                                                          "org.jooq.util.h2.H2DataType",
                                                                          "org.jooq.util.hsqldb.HSQLDBDataType",
                                                                          "org.jooq.util.mariadb.MariaDBDataType",
                                                                          "org.jooq.util.mysql.MySQLDataType",
                                                                          "org.jooq.util.postgres.PostgresDataType",
                                                                          "org.jooq.util.sqlite.SQLiteDataType",
                                                                          "org.jooq.impl.SQLDataType",
                                                                          "org.jooq.impl.AbstractField",
                                                                          "org.jooq.impl.TableFieldImpl",
                                                                          "org.jooq.tools.StringUtils",
                                                                          "com.chiralbehaviors.CoRE.jooq.tables.Existential",
                                                                          "org.jooq.impl.RowImpl",
                                                                          "com.chiralbehaviors.CoRE.domain.Unit",
                                                                          "com.chiralbehaviors.CoRE.domain.Relationship",
                                                                          "com.chiralbehaviors.CoRE.domain.Agency",
                                                                          "org.jooq.impl.Tools",
                                                                          "org.jooq.impl.DefaultConfiguration",
                                                                          "org.jooq.conf.SettingsBase",
                                                                          "org.jooq.conf.Settings",
                                                                          "org.jooq.conf.RenderNameStyle",
                                                                          "org.jooq.conf.RenderKeywordStyle",
                                                                          "org.jooq.conf.BackslashEscaping",
                                                                          "org.jooq.conf.ParamType",
                                                                          "org.jooq.conf.StatementType",
                                                                          "org.jooq.conf.SettingsTools",
                                                                          "org.jooq.SchemaMapping",
                                                                          "org.jooq.impl.DefaultDSLContext",
                                                                          "org.jooq.impl.DefaultRenderContext",
                                                                          "org.jooq.impl.Tools$DataKey",
                                                                          "org.jooq.RenderContext$CastMode",
                                                                          "org.jooq.conf.RenderMapping",
                                                                          "org.jooq.impl.Identifiers$1",
                                                                          "org.jooq.impl.Identifiers",
                                                                          "com.chiralbehaviors.CoRE.domain.Location");
    }

    private org.evosuite.runtime.thread.ThreadStopper threadStopper = new org.evosuite.runtime.thread.ThreadStopper(org.evosuite.runtime.thread.KillSwitchHandler.getInstance(),
                                                                                                                    3000);

    @After
    public void doneWithTestCase() {
        threadStopper.killAndJoinClientThreads();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance()
                                                    .safeExecuteAddedHooks();
        org.evosuite.runtime.classhandling.JDKClassResetter.reset();
        resetClasses();
        org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
        org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
        org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
    }

    @Before
    public void initTestCase() {
        threadStopper.storeCurrentThreads();
        threadStopper.startRecordingTime();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance()
                                                    .initHandler();
        org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
        org.evosuite.runtime.GuiSupport.setHeadless();
        org.evosuite.runtime.Runtime.getInstance()
                                    .resetRuntime();
        org.evosuite.runtime.agent.InstrumentingAgent.activate();
    }

    public void setSystemProperties() {

        /*No java.lang.System property to set*/
    }
}
