/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 08 20:24:50 GMT 2016
 */

package com.chiralbehaviors.CoRE.domain;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Location_ESTest extends Location_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        new Location();
    }
}
