/**
 * AUTOGENERATED! DO NOT EDIT BY HAND.
 * Generated by PolymorphicMixinGenerator.java
 * 
 */
package com.chiralbehaviors.CoRE.json;

import com.chiralbehaviors.CoRE.agency.Agency;
import com.chiralbehaviors.CoRE.agency.AgencyAttribute;
import com.chiralbehaviors.CoRE.agency.AgencyAttributeAuthorization;
import com.chiralbehaviors.CoRE.agency.AgencyLocation;
import com.chiralbehaviors.CoRE.agency.AgencyLocationAttribute;
import com.chiralbehaviors.CoRE.agency.AgencyLocationAttributeAuthorization;
import com.chiralbehaviors.CoRE.agency.AgencyLocationAuthorization;
import com.chiralbehaviors.CoRE.agency.AgencyNetwork;
import com.chiralbehaviors.CoRE.agency.AgencyNetworkAttribute;
import com.chiralbehaviors.CoRE.agency.AgencyNetworkAuthorization;
import com.chiralbehaviors.CoRE.agency.AgencyProduct;
import com.chiralbehaviors.CoRE.agency.AgencyProductAttribute;
import com.chiralbehaviors.CoRE.agency.AgencyProductAttributeAuthorization;
import com.chiralbehaviors.CoRE.agency.AgencyProductAuthorization;
import com.chiralbehaviors.CoRE.attribute.Attribute;
import com.chiralbehaviors.CoRE.attribute.AttributeMetaAttribute;
import com.chiralbehaviors.CoRE.attribute.AttributeMetaAttributeAuthorization;
import com.chiralbehaviors.CoRE.attribute.AttributeNetwork;
import com.chiralbehaviors.CoRE.attribute.AttributeNetworkAttribute;
import com.chiralbehaviors.CoRE.attribute.AttributeNetworkAuthorization;
import com.chiralbehaviors.CoRE.attribute.unit.Unit;
import com.chiralbehaviors.CoRE.attribute.unit.UnitAttribute;
import com.chiralbehaviors.CoRE.attribute.unit.UnitAttributeAuthorization;
import com.chiralbehaviors.CoRE.attribute.unit.UnitNetwork;
import com.chiralbehaviors.CoRE.attribute.unit.UnitNetworkAttribute;
import com.chiralbehaviors.CoRE.attribute.unit.UnitNetworkAuthorization;
import com.chiralbehaviors.CoRE.job.Job;
import com.chiralbehaviors.CoRE.job.JobChronology;
import com.chiralbehaviors.CoRE.job.MetaProtocol;
import com.chiralbehaviors.CoRE.job.ProductChildSequencingAuthorization;
import com.chiralbehaviors.CoRE.job.ProductParentSequencingAuthorization;
import com.chiralbehaviors.CoRE.job.ProductSelfSequencingAuthorization;
import com.chiralbehaviors.CoRE.job.ProductSiblingSequencingAuthorization;
import com.chiralbehaviors.CoRE.job.Protocol;
import com.chiralbehaviors.CoRE.job.status.StatusCode;
import com.chiralbehaviors.CoRE.job.status.StatusCodeAttribute;
import com.chiralbehaviors.CoRE.job.status.StatusCodeAttributeAuthorization;
import com.chiralbehaviors.CoRE.job.status.StatusCodeNetwork;
import com.chiralbehaviors.CoRE.job.status.StatusCodeNetworkAttribute;
import com.chiralbehaviors.CoRE.job.status.StatusCodeNetworkAuthorization;
import com.chiralbehaviors.CoRE.job.status.StatusCodeSequencing;
import com.chiralbehaviors.CoRE.location.Location;
import com.chiralbehaviors.CoRE.location.LocationAttribute;
import com.chiralbehaviors.CoRE.location.LocationAttributeAuthorization;
import com.chiralbehaviors.CoRE.location.LocationNetwork;
import com.chiralbehaviors.CoRE.location.LocationNetworkAttribute;
import com.chiralbehaviors.CoRE.location.LocationNetworkAuthorization;
import com.chiralbehaviors.CoRE.network.NetworkInference;
import com.chiralbehaviors.CoRE.product.Product;
import com.chiralbehaviors.CoRE.product.ProductAttribute;
import com.chiralbehaviors.CoRE.product.ProductAttributeAuthorization;
import com.chiralbehaviors.CoRE.product.ProductLocation;
import com.chiralbehaviors.CoRE.product.ProductLocationAttribute;
import com.chiralbehaviors.CoRE.product.ProductLocationAttributeAuthorization;
import com.chiralbehaviors.CoRE.product.ProductLocationAuthorization;
import com.chiralbehaviors.CoRE.product.ProductNetwork;
import com.chiralbehaviors.CoRE.product.ProductNetworkAttribute;
import com.chiralbehaviors.CoRE.product.ProductNetworkAuthorization;
import com.chiralbehaviors.CoRE.product.ProductRelationship;
import com.chiralbehaviors.CoRE.product.ProductRelationshipAttribute;
import com.chiralbehaviors.CoRE.relationship.Relationship;
import com.chiralbehaviors.CoRE.relationship.RelationshipAttribute;
import com.chiralbehaviors.CoRE.relationship.RelationshipAttributeAuthorization;
import com.chiralbehaviors.CoRE.relationship.RelationshipNetwork;
import com.chiralbehaviors.CoRE.relationship.RelationshipNetworkAttribute;
import com.chiralbehaviors.CoRE.relationship.RelationshipNetworkAuthorization;
import com.chiralbehaviors.CoRE.time.Interval;
import com.chiralbehaviors.CoRE.time.IntervalAttribute;
import com.chiralbehaviors.CoRE.time.IntervalAttributeAuthorization;
import com.chiralbehaviors.CoRE.time.IntervalNetwork;
import com.chiralbehaviors.CoRE.time.IntervalNetworkAttribute;
import com.chiralbehaviors.CoRE.time.IntervalNetworkAuthorization;
import com.chiralbehaviors.CoRE.workspace.WorkspaceAuthorization;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type")
@JsonSubTypes({ @Type(value = ProductChildSequencingAuthorization.class),
                @Type(value = StatusCode.class),
                @Type(value = StatusCodeNetwork.class),
                @Type(value = ProductAttributeAuthorization.class),
                @Type(value = IntervalNetworkAuthorization.class),
                @Type(value = NetworkInference.class),
                @Type(value = AgencyLocationAttributeAuthorization.class),
                @Type(value = UnitNetworkAttribute.class),
                @Type(value = RelationshipAttributeAuthorization.class),
                @Type(value = LocationAttributeAuthorization.class),
                @Type(value = AgencyProduct.class),
                @Type(value = AttributeMetaAttribute.class),
                @Type(value = Interval.class),
                @Type(value = RelationshipNetworkAuthorization.class),
                @Type(value = WorkspaceAuthorization.class),
                @Type(value = JobChronology.class),
                @Type(value = IntervalNetwork.class),
                @Type(value = IntervalAttribute.class),
                @Type(value = AttributeMetaAttributeAuthorization.class),
                @Type(value = StatusCodeNetworkAuthorization.class),
                @Type(value = ProductRelationshipAttribute.class),
                @Type(value = StatusCodeAttribute.class),
                @Type(value = StatusCodeAttributeAuthorization.class),
                @Type(value = UnitNetwork.class), @Type(value = Job.class),
                @Type(value = RelationshipNetwork.class),
                @Type(value = ProductParentSequencingAuthorization.class),
                @Type(value = LocationNetworkAttribute.class),
                @Type(value = AgencyNetworkAuthorization.class),
                @Type(value = StatusCodeNetworkAttribute.class),
                @Type(value = ProductNetworkAuthorization.class),
                @Type(value = ProductLocationAttribute.class),
                @Type(value = UnitAttribute.class),
                @Type(value = AgencyNetwork.class),
                @Type(value = AgencyLocationAttribute.class),
                @Type(value = AgencyProductAuthorization.class),
                @Type(value = Protocol.class), @Type(value = Product.class),
                @Type(value = ProductRelationship.class),
                @Type(value = Attribute.class),
                @Type(value = RelationshipAttribute.class),
                @Type(value = UnitAttributeAuthorization.class),
                @Type(value = ProductLocationAttributeAuthorization.class),
                @Type(value = AttributeNetwork.class),
                @Type(value = IntervalNetworkAttribute.class),
                @Type(value = AttributeNetworkAttribute.class),
                @Type(value = ProductNetwork.class),
                @Type(value = MetaProtocol.class),
                @Type(value = LocationAttribute.class),
                @Type(value = LocationNetwork.class),
                @Type(value = ProductAttribute.class),
                @Type(value = Location.class),
                @Type(value = AgencyLocation.class),
                @Type(value = AgencyAttribute.class),
                @Type(value = UnitNetworkAuthorization.class),
                @Type(value = Relationship.class),
                @Type(value = IntervalAttributeAuthorization.class),
                @Type(value = AgencyProductAttribute.class),
                @Type(value = ProductLocation.class), @Type(value = Unit.class),
                @Type(value = AgencyLocationAuthorization.class),
                @Type(value = ProductNetworkAttribute.class),
                @Type(value = RelationshipNetworkAttribute.class),
                @Type(value = AgencyProductAttributeAuthorization.class),
                @Type(value = AgencyNetworkAttribute.class),
                @Type(value = ProductSiblingSequencingAuthorization.class),
                @Type(value = StatusCodeSequencing.class),
                @Type(value = ProductSelfSequencingAuthorization.class),
                @Type(value = LocationNetworkAuthorization.class),
                @Type(value = AttributeNetworkAuthorization.class),
                @Type(value = Agency.class),
                @Type(value = AgencyAttributeAuthorization.class),
                @Type(value = ProductLocationAuthorization.class),

})
public abstract class PolymorphicRuleformMixin {
}
