auth: NULL_AUTH


database:
    driverClass: org.postgresql.Driver
    maxSize: 20
        
logging:
    level: INFO
    loggers: 
        "org.glassfish": ERROR
        graphql: WARN

workspaces:
  - /com/chiralbehaviors/CoRE/universal/single-page.1.json
