auth: NULL_AUTH


database:
    driverClass: org.postgresql.Driver
    maxSize: 20
        
logging:
    level: INFO
    loggers: 
        org.glassfish: ERROR
        graphql: WARN
        de.flapdoodle: WARN

workspaces:
  - /com/chiralbehaviors/CoRE/universal/single-page.1.json
  - /acm-95.1.json
  - /thing.1.json
