/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 08 20:29:59 GMT 2016
 */

package com.chiralbehaviors.CoRE.workspace;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import java.util.Collection;
import java.util.UUID;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jooq.DSLContext;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class StateSnapshot_ESTest extends StateSnapshot_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        try {
            new StateSnapshot((DSLContext) null, (Collection<UUID>) null);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            assertThrownBy("com.chiralbehaviors.CoRE.workspace.StateSnapshot",
                           e);
        }
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        // Undeclared exception!
        try {
            StateSnapshot.selectNullClosure((DSLContext) null,
                                            (Collection<UUID>) null);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            assertThrownBy("com.chiralbehaviors.CoRE.workspace.StateSnapshot",
                           e);
        }
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        StateSnapshot stateSnapshot0 = new StateSnapshot();
        stateSnapshot0.loadDefiningProduct((DSLContext) null);
    }
}
