/**
 * Scaffolding file used to store all the setups needed to run
 * tests automatically generated by EvoSuite
 * Fri Apr 08 20:17:50 GMT 2016
 */

package com.chiralbehaviors.CoRE.postgres;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@EvoSuiteClassExclude
public class PostgresJSONJacksonJsonNodeBinding_ESTest_scaffolding {

    private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties()
                                                                                                         .clone();

    @AfterClass
    public static void clearEvoSuiteFramework() {
        Sandbox.resetDefaultSecurityManager();
        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    }

    @BeforeClass
    public static void initEvoSuiteFramework() {
        org.evosuite.runtime.RuntimeSettings.className = "com.chiralbehaviors.CoRE.postgres.PostgresJSONJacksonJsonNodeBinding";
        org.evosuite.runtime.GuiSupport.initialize();
        org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
        org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
        org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
        org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
        org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
        org.evosuite.runtime.classhandling.JDKClassResetter.init();
        initializeClasses();
        org.evosuite.runtime.Runtime.getInstance()
                                    .resetRuntime();
    }

    private static void initializeClasses() {
        org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(PostgresJSONJacksonJsonNodeBinding_ESTest_scaffolding.class.getClassLoader(),
                                                                               "org.jooq.impl.RecordOperation",
                                                                               "org.jooq.BindingRegisterContext",
                                                                               "com.fasterxml.jackson.databind.JsonSerializable$Base",
                                                                               "org.jooq.types.UShort",
                                                                               "org.jooq.Converters",
                                                                               "org.postgresql.core.Logger",
                                                                               "com.fasterxml.jackson.databind.node.NullNode",
                                                                               "org.hsqldb.jdbc.JDBCDriver",
                                                                               "org.jooq.RenderContext",
                                                                               "org.jooq.Binding",
                                                                               "com.chiralbehaviors.CoRE.postgres.PostgresJSONJacksonJsonNodeBinding",
                                                                               "org.jooq.types.UInteger",
                                                                               "org.jooq.SelectField",
                                                                               "org.postgresql.util.SharedTimer",
                                                                               "org.jooq.impl.DefaultDataType",
                                                                               "org.jooq.FieldOrRow",
                                                                               "com.fasterxml.jackson.databind.node.BaseJsonNode",
                                                                               "com.fasterxml.jackson.databind.JsonSerializable",
                                                                               "com.fasterxml.jackson.databind.JsonNode",
                                                                               "org.jooq.util.cubrid.CUBRIDDataType",
                                                                               "org.jooq.types.UNumber",
                                                                               "org.jooq.types.UByte",
                                                                               "org.jooq.exception.DataTypeException",
                                                                               "org.jooq.Scope",
                                                                               "org.jooq.SQLDialect",
                                                                               "com.chiralbehaviors.CoRE.postgres.PostgresJSONJacksonJsonNodeConverter",
                                                                               "org.hsqldb.jdbc.JDBCDriver$1",
                                                                               "org.jooq.BindingSetSQLOutputContext",
                                                                               "org.jooq.GroupField",
                                                                               "org.jooq.DataType",
                                                                               "org.jooq.tools.JooqLogger",
                                                                               "org.jooq.exception.SQLDialectNotSupportedException",
                                                                               "org.jooq.Field",
                                                                               "org.jooq.exception.MappingException",
                                                                               "org.jooq.Result",
                                                                               "org.jooq.QueryPart",
                                                                               "com.fasterxml.jackson.databind.node.ValueNode",
                                                                               "org.jooq.util.postgres.PostgresDataType",
                                                                               "org.jooq.util.hsqldb.HSQLDBDataType",
                                                                               "org.jooq.Context",
                                                                               "org.jooq.impl.SQLDataType",
                                                                               "org.jooq.BindingSQLContext",
                                                                               "org.jooq.BindingGetSQLInputContext",
                                                                               "org.jooq.util.firebird.FirebirdDataType",
                                                                               "org.jooq.types.DayToSecond",
                                                                               "org.jooq.util.derby.DerbyDataType",
                                                                               "org.postgresql.util.HostSpec",
                                                                               "org.jooq.BindingGetResultSetContext",
                                                                               "org.postgresql.util.PSQLException",
                                                                               "org.jooq.impl.DefaultBinding",
                                                                               "org.jooq.util.h2.H2DataType",
                                                                               "org.jooq.types.Interval",
                                                                               "com.fasterxml.jackson.core.TreeNode",
                                                                               "org.jooq.exception.DataAccessException",
                                                                               "org.jooq.Record",
                                                                               "org.jooq.BindingSetStatementContext",
                                                                               "org.jooq.Attachable",
                                                                               "org.jooq.util.mysql.MySQLDataType",
                                                                               "org.jooq.types.ULong",
                                                                               "org.jooq.Converter",
                                                                               "org.jooq.types.YearToMonth",
                                                                               "org.jooq.util.mariadb.MariaDBDataType",
                                                                               "org.jooq.Configuration",
                                                                               "org.jooq.BindingGetStatementContext",
                                                                               "org.jooq.SQLDialect$ThirdParty",
                                                                               "org.jooq.Converters$1",
                                                                               "org.jooq.util.sqlite.SQLiteDataType",
                                                                               "org.postgresql.Driver");
    }

    private static void resetClasses() {
        org.evosuite.runtime.classhandling.ClassResetter.getInstance()
                                                        .setClassLoader(PostgresJSONJacksonJsonNodeBinding_ESTest_scaffolding.class.getClassLoader());

        org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses("com.chiralbehaviors.CoRE.postgres.PostgresJSONJacksonJsonNodeBinding",
                                                                          "org.jooq.SQLDialect",
                                                                          "org.jooq.impl.DefaultDataType",
                                                                          "org.jooq.impl.DefaultBinding",
                                                                          "org.jooq.Converters",
                                                                          "org.jooq.Converters$1",
                                                                          "org.jooq.util.cubrid.CUBRIDDataType",
                                                                          "org.jooq.util.derby.DerbyDataType",
                                                                          "org.jooq.util.firebird.FirebirdDataType",
                                                                          "org.jooq.util.h2.H2DataType",
                                                                          "org.jooq.util.hsqldb.HSQLDBDataType",
                                                                          "org.jooq.util.mariadb.MariaDBDataType",
                                                                          "org.jooq.util.mysql.MySQLDataType",
                                                                          "org.jooq.util.postgres.PostgresDataType",
                                                                          "org.jooq.util.sqlite.SQLiteDataType",
                                                                          "org.jooq.impl.SQLDataType",
                                                                          "com.chiralbehaviors.CoRE.postgres.PostgresJSONJacksonJsonNodeConverter",
                                                                          "org.postgresql.util.SharedTimer",
                                                                          "org.postgresql.Driver",
                                                                          "org.hsqldb.jdbc.JDBCDriver");
    }

    private org.evosuite.runtime.thread.ThreadStopper threadStopper = new org.evosuite.runtime.thread.ThreadStopper(org.evosuite.runtime.thread.KillSwitchHandler.getInstance(),
                                                                                                                    3000);

    @After
    public void doneWithTestCase() {
        threadStopper.killAndJoinClientThreads();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance()
                                                    .safeExecuteAddedHooks();
        org.evosuite.runtime.classhandling.JDKClassResetter.reset();
        resetClasses();
        org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
        org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
        org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
    }

    @Before
    public void initTestCase() {
        threadStopper.storeCurrentThreads();
        threadStopper.startRecordingTime();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance()
                                                    .initHandler();
        org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
        setSystemProperties();
        org.evosuite.runtime.GuiSupport.setHeadless();
        org.evosuite.runtime.Runtime.getInstance()
                                    .resetRuntime();
        org.evosuite.runtime.agent.InstrumentingAgent.activate();
    }

    public void setSystemProperties() {

        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
        java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation");
        java.lang.System.setProperty("java.specification.version", "1.8");
        java.lang.System.setProperty("java.home",
                                     "/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre");
        java.lang.System.setProperty("java.awt.headless", "true");
        java.lang.System.setProperty("user.home", "/Users/hhildebrand");
        java.lang.System.setProperty("user.dir",
                                     "/Users/hhildebrand/git/Ultrastructure/model");
        java.lang.System.setProperty("java.io.tmpdir",
                                     "/var/folders/_r/y4_0rwd16zgblwjq7b_tbhk80000gn/T/");
        java.lang.System.setProperty("awt.toolkit",
                                     "sun.lwawt.macosx.LWCToolkit");
        java.lang.System.setProperty("file.encoding", "UTF-8");
        java.lang.System.setProperty("file.separator", "/");
        java.lang.System.setProperty("java.awt.graphicsenv",
                                     "sun.awt.CGraphicsEnvironment");
        java.lang.System.setProperty("java.awt.printerjob",
                                     "sun.lwawt.macosx.CPrinterJob");
        java.lang.System.setProperty("java.class.path",
                                     "/var/folders/_r/y4_0rwd16zgblwjq7b_tbhk80000gn/T/EvoSuite_pathingJar3221804729915791195.jar");
        java.lang.System.setProperty("java.class.version", "52.0");
        java.lang.System.setProperty("java.endorsed.dirs",
                                     "/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/endorsed");
        java.lang.System.setProperty("java.ext.dirs",
                                     "/Users/hhildebrand/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java");
        java.lang.System.setProperty("java.library.path", "lib");
        java.lang.System.setProperty("java.runtime.name",
                                     "Java(TM) SE Runtime Environment");
        java.lang.System.setProperty("java.runtime.version", "1.8.0_45-b14");
        java.lang.System.setProperty("java.specification.name",
                                     "Java Platform API Specification");
        java.lang.System.setProperty("java.specification.vendor",
                                     "Oracle Corporation");
        java.lang.System.setProperty("java.vendor", "Oracle Corporation");
        java.lang.System.setProperty("java.vendor.url",
                                     "http://java.oracle.com/");
        java.lang.System.setProperty("java.version", "1.8.0_45");
        java.lang.System.setProperty("java.vm.info", "mixed mode");
        java.lang.System.setProperty("java.vm.name",
                                     "Java HotSpot(TM) 64-Bit Server VM");
        java.lang.System.setProperty("java.vm.specification.name",
                                     "Java Virtual Machine Specification");
        java.lang.System.setProperty("java.vm.specification.vendor",
                                     "Oracle Corporation");
        java.lang.System.setProperty("java.vm.specification.version", "1.8");
        java.lang.System.setProperty("java.vm.version", "25.45-b02");
        java.lang.System.setProperty("line.separator", "\n");
        java.lang.System.setProperty("os.arch", "x86_64");
        java.lang.System.setProperty("os.name", "Mac OS X");
        java.lang.System.setProperty("os.version", "10.11.3");
        java.lang.System.setProperty("path.separator", ":");
        java.lang.System.setProperty("user.country", "US");
        java.lang.System.setProperty("user.language", "en");
        java.lang.System.setProperty("user.name", "hhildebrand");
        java.lang.System.setProperty("user.timezone", "America/Los_Angeles");
    }
}
